### ISSUE TITLE
Unable to use the package using a non-default namespace

### ISSUE THREAD

**Issue by yoyosan** [WebDevEtc/BlogEtc#13]
Hey.

I'm unable to use the package with a namespace different from `App`.

![image](https://user-images.githubusercontent.com/32405/61994658-08b9a080-b086-11e9-893b-2e2c23c49a3b.png)

A temporary fix is to modify it in the package every time you fetch a new version.

**Comment by WebDevEtc** [comment]
Hi,
Hmmm, not really sure that there is a reasonable fix for this. 
I'm currently rewriting the package (release soon, just taking a while due to work getting in the way :) )... \App\Http\controllers\Controller is there by standard in any laravel install. I guess you could create a class with that namespace, and just have it extend Illuminate\Routing\Controller

**Comment by yoyosan** [comment]
I wonder whether publishing controllers and telling users to fix the namespace would do it.

I'll test locally and let you know.

LE: I'm in vacation right now, it will take a while until I'll test this.

**Comment by cavewebs** [comment]
This happened to me but it is with the Authorization. 
So my namespace is `App/Models/User ` so the canManageBlogEtc() function does not work

**Comment by yoyosan** [comment]
Sorry for being back so late to this.

I still don't know a good way to fix this issue.

After some consideration and looking at Laravel 6 removing the `app:namespace` command, I've realized that you should have the `App` namespace. There's nothing special in having `YourOrganization` or `YourApp` namespace.
